# Generated by Django 5.1 on 2025-03-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='accommodation_property_id_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='accommodation_property_id_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='accommodation_property_id_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
