# Generated by Django 5.1 on 2024-12-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_holiday_holiday_image1_holiday_holiday_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_image1',
<<<<<<< HEAD
            field=models.CharField(max_length=500, blank=True, null=True),
=======
            field=models.CharField(blank=True, null=True),
>>>>>>> 9f8ffbc (Changes in prod.)
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_image2',
<<<<<<< HEAD
            field=models.CharField(max_length=500, blank=True, null=True),
=======
            field=models.CharField(blank=True, null=True),
>>>>>>> 9f8ffbc (Changes in prod.)
        ),
    ]
