# Generated by Django 5.1 on 2025-03-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_alter_holiday_accommodation_property_id_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='cities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
