# Generated by Django 5.1 on 2024-11-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_reset_password_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
