# Generated by Django 5.1 on 2024-08-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_cost_per_night'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/image')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='propertyImage', to='property.property')),
            ],
        ),
    ]
