# Generated by Django 5.1 on 2024-09-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='img',
        ),
        migrations.AddField(
            model_name='property',
            name='address1',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom1_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom2_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom3_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom4_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='great_for',
            field=models.CharField(choices=[('senior_citizen', 'Senior Citizen'), ('kids', 'Kids'), ('adults', 'Adults'), ('all', 'All of the Above'), ('Others', 'others')], default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='guest_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='meals_available',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='num_bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='num_bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='other_images',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pincode',
            field=models.CharField(default='Enter Pincode', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Bungalow', 'Bungalow'), ('Hotel', 'Hotel')], default='Select Property Type', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='Add Title', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='total_bedroom_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_key_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
