# Generated by Django 5.1 on 2024-10-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_img_property_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description1',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='property',
            name='description2',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='property',
            name='description3',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='property',
            name='description4',
            field=models.TextField(default='No description available'),
        ),
    ]
