# Generated by Django 5.1 on 2024-10-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_description1_property_description2_and_more'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='property',
    #         name='description',
    #     ),
    # ]
