# Generated by Django 5.1 on 2024-10-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
    ]
