# Generated by Django 5.1 on 2024-10-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
