# Generated by Django 5.1.1 on 2024-10-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedroom1_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom2_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom3_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom4_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='other_images',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
