# Generated by Django 5.1.1 on 2024-10-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_property_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='property/image/'),
        ),
    ]
