# Generated by Django 5.1.1 on 2024-10-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_property_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
