# Generated by Django 5.1.1 on 2024-10-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_property_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='price_room',
        ),
        migrations.AddField(
            model_name='property',
            name='num_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='price_villa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
