# Generated by Django 5.1 on 2024-10-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_property_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedroom1_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom2_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom3_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom4_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='other_images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
