# Generated by Django 5.1 on 2024-10-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_property_bedroom1_image_and_more'),
        ('property', '0013_rename_price_property_price_room_property_num_rooms_and_more'),
    ]

    operations = [
    ]
