# Generated by Django 5.1.1 on 2024-10-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
