# Generated by Django 5.1.1 on 2024-10-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_property_video_url_alter_property_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='best_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='most_loved',
            field=models.BooleanField(default=False),
        ),
    ]
