# Generated by Django 5.1 on 2024-10-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_property_best_rated_property_most_loved'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
