# Generated by Django 5.1 on 2024-10-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_property_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent_id',
        ),
    ]
