# Generated by Django 5.1.1 on 2024-10-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_property_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='great_for',
            field=models.CharField(choices=[('Senior Citizen', 'Senior Citizen'), ('Kids', 'Kids'), ('Adults', 'Adults'), ('All', 'All'), ('Others', 'others')], default='all', max_length=50),
        ),
    ]
