# Generated by Django 5.1 on 2024-11-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_alter_property_description1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='description3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='description4',
            field=models.TextField(default=''),
        ),
    ]
