# Generated by Django 5.1 on 2024-11-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_property_img2_property_room_name_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
