# Generated by Django 5.1.1 on 2024-09-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('concern', models.CharField(choices=[('New Booking', 'New Booking'), ('Existing Booking', 'Existing Booking'), ('Upcoming Booking', 'Upcoming Booking')], max_length=50)),
                ('property_location', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'enquiries',
            },
        ),
    ]
