# Generated by Django 5.1 on 2025-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('num_guests', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('propertyId', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('agentId', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('concern', models.CharField(blank=True, choices=[('New Booking', 'New Booking'), ('Existing Booking', 'Existing Booking'), ('Upcoming Booking', 'Upcoming Booking')], max_length=50, null=True)),
                ('property_location', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enquiries',
            },
        ),
    ]
