# Generated by Django 5.1 on 2024-11-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='check_in_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='check_out_date',
            field=models.DateField(blank=True, default='2000-01-02', null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
