# Generated by Django 5.1 on 2024-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_enquiry_check_in_date_enquiry_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='num_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
