# Generated by Django 5.1 on 2024-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_rename_num_rooms_enquiry_num_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='propertyId',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
