# Generated by Django 5.1 on 2024-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_alter_enquiry_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='agentId',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
