# Generated by Django 5.1 on 2024-10-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('event_organizer', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_location', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'eventdata',
            },
        ),
    ]
