# Generated by Django 5.1 on 2024-10-11 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('organizer_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='00:00:00')),
                ('location', models.CharField(default='Add location', max_length=255)),
                ('address1', models.CharField(default='Add address1', max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(default='Add city', max_length=255)),
                ('state', models.CharField(default='Add state', max_length=255)),
                ('country', models.CharField(default='Add country', max_length=255)),
                ('postalcode', models.CharField(default='000000', max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
                ('image3', models.TextField(blank=True, null=True)),
                ('contactname', models.CharField(default='Add contact name', max_length=255)),
                ('contactnumber', models.CharField(default='Add contact number', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Add category', max_length=100)),
            ],
            options={
                'db_table': 'eventdata',
            },
        ),
    ]
