# Generated by Django 5.1 on 2024-11-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_alter_destination_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='order_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
