# Generated by Django 5.1 on 2024-09-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('org_id', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_investor', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Investors',
            },
        ),
        migrations.CreateModel(
            name='InvestorLogs',
            fields=[
                ('logid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(max_length=500)),
                ('mode', models.CharField(max_length=100)),
                ('log_message', models.TextField()),
                ('is_app', models.BooleanField(default=False)),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='log_investor_id', to='investors.investors')),
            ],
            options={
                'db_table': 'InvestorLogs',
            },
        ),
    ]
