# Generated by Django 5.1 on 2025-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(default='default@example.com', max_length=254)),
                ('customer_mobile_no', models.CharField(max_length=15)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField(blank=True, null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('propertyId', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('agentId', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('num_guests', models.IntegerField(default=1)),
                ('num_rooms', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customers', models.ManyToManyField(to='booking.customer')),
            ],
        ),
    ]
