# Generated by Django 5.1 on 2024-10-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_email_remove_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='property_type',
        ),
    ]
