# Generated by Django 5.1 on 2024-10-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_eventbooking_booking_date_eventbooking_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='booking_date',
        ),
    ]
