# Generated by Django 5.1.1 on 2024-10-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile_no',
            new_name='age',
        ),
    ]
