# Generated by Django 5.1.1 on 2024-10-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_rename_customer_guest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='customers',
        ),
    ]
