# Generated by Django 5.1 on 2024-10-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_customer_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='org_id',
        ),
    ]
