# Generated by Django 5.1 on 2024-11-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
