# Generated by Django 5.1 on 2024-11-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_remove_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agentId',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='propertyId',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
