name: Deploy

on:
  push:
    branches: [ main ]


jobs:
  Deploy-quantbotsco-server1:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 

      - name: Install SSHpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to digitalocean
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          HOSTNAME: apollotravels.co
          USER_NAME: ${{ secrets.SSH_USER }}

        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} << 'EOF'
            cd /home/ubuntu/repos/stayvillas-api
            ./scripts/deployapi_ns1.sh stayvillas
          EOF